### PR TITLE
vector_tile_geometry_decoder - only drop 'degenerate' rings

### PR DESCRIPTION
**Pull request by artemp**

### CODE REVIEW

**Comment by springmeyer** [comment]
per chat with @artemp - this fixes the decoders ability to handle agg-clipped geometries in all testcases seen so far where they were previously rendering incorrectly. Before merging this needs:

  - [ ] regression testcase (@artemp)
  - [ ] a bit more manual testing of styles previously affected in studio (@springmeyer) to ensure it looks good
  - [ ] this work will obsolete the untested `treat_all_rings_as_exterior` option which was originally designed to address this issue.

**Comment by artemp** [comment]
@springmeyer - example data from v4
https://gist.github.com/artemp/5ac35d65e3e89d2cef42

**Comment by springmeyer** [comment]
per chat with @artemp - I'll test this later this afternoon and run through some new unit tests I've been writing that:

 - test multiple mapnik versions
 - test multiple versions of vector tiles (generated with agg clipper and angus clipper)
 - using the same style

**Comment by springmeyer** [comment]
confirmed this is fixed, awesome work @artemp:

before:

pinterest-stamen-print-3-2-3-3 3 1-offset

after:

pinterest-stamen-print-3-2-3-3 3 1

**Pull request merged**
