### PR TITLE
Update to latest Mapnik API

### PR DESCRIPTION
**Pull request by david-springer**
Update tests and benchmark code to the latest mapnik::util::file API -
changed calls to file::is_open() to file::open().

Also updated the golden images for fixtures test.

`make test` now runs cleanly on my El Capitan Mac.

### CODE REVIEW

**Comment by pnorman** [comment]
Would this break compatibility with some versions of Mapnik?

**Comment by david-springer** [comment]
@pnorman: Good question. The version of Mapnik that was installed via `brew install --with-gdal` did not have the file::is_open() API - it has file::open() instead. The golden image update might break things, though. I ran all this on my Mac (El Cap 10.11.4) with these versions of clang and mapnik:
```
areyoukidding:mapnik-vector-tile daves$ **clang --version**
Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin15.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
areyoukidding:mapnik-vector-tile daves$ **brew list mapnik**
/usr/local/Cellar/mapnik/3.0.9/bin/mapnik-config
/usr/local/Cellar/mapnik/3.0.9/bin/mapnik-index
/usr/local/Cellar/mapnik/3.0.9/bin/mapnik-render
/usr/local/Cellar/mapnik/3.0.9/bin/shapeindex
/usr/local/Cellar/mapnik/3.0.9/include/mapnik/ (444 files)
/usr/local/Cellar/mapnik/3.0.9/lib/libmapnik.dylib
/usr/local/Cellar/mapnik/3.0.9/lib/mapnik/ (30 files)
/usr/local/Cellar/mapnik/3.0.9/lib/ (2 other files)
```

**Comment by pnorman** [comment]
> The version of Mapnik that was installed via brew install --with-gdal did not have the file::is_open() API - it has file::open() instead

If an API present in 3.0.x (x<9) is not present in 3.0.9 then this is a Mapnik bug as it violates [their versioning](https://github.com/mapnik/mapnik/issues/3372) and should be solved there.

**Comment by david-springer** [comment]
@pnorman Point taken. Maybe the best way for me to proceed is to work in my fork - these changes affect test code and not the core code of the tiler.

I'll close this PR for now, and maybe open a Mapnik issue about this API change. Thanks!

**Pull request closed without merging**
