### PR TITLE
Update for mapnik v3.1.x (master)

### PR DESCRIPTION
**Pull request by springmeyer**
Gets mapnik-vector-tile compiling against mapnik master (future 3.1)

### CODE REVIEW

**Comment by springmeyer** [comment]
@artemp as you work on this next week, make sure to rebase against master after #253 landes - that will help build/test this locally without needing to test via node-mapnik (important since there is critical test coverage here).

**Comment by springmeyer** [comment]
> make sure to rebase against master after #253 lands

I went ahead and did this. So now this branch is up to date against master.

**Comment by springmeyer** [comment]
This branch is looking good so far. Tests are passing locally. The remaining work to do is to update the mason package ref such that travis will pass.

refs https://github.com/mapnik/node-mapnik/pull/805

**Comment by springmeyer** [comment]
@artemp I think you just pushed Mapnik 3.1.x changes to master? How do they relate to this branch?

**Comment by artemp** [comment]
@springmeyer - `make-strict-an-option-master` is a `master` now. `v3.0.x` is based on old master. Sorry, I'm not following your question?

**Comment by springmeyer** [comment]
@artemp This PR is for merging `make-strict-an-option-master` into master. Sounds like you did that already. So my question is: can this be closed? It seems like you merged somehow differently than merging this PR - if so did you capture everything in this PR?

**Comment by springmeyer** [comment]
I think everything in this PR is already in master, closing.

**Pull request closed without merging**
