### PR TITLE
Add fields_to_exclude to start_tile_feature()

### PR DESCRIPTION
**Pull request by ljbade**
Closes https://github.com/mapbox/mapnik-vector-tile/issues/77

@springmeyer Is this what you had in mind?

Needs a test case.

### CODE REVIEW

**Comment by springmeyer** [comment]
looks good for testing your optimization. we should also consider the alternative design of accepting a list of fields to include. I'd need to mull on this more to have a strong opinion. 

while I'm brainstorming: The other thing we should add is filtering support such that you could pass down a 'mapnik::expression' string to be evaluated and throw out features not matching. the goal of this would be to allow rudimentary filtering support for datasource other than Postgres.

**Comment by ljbade** [comment]
@springmeyer I will have to read up on Mapnik expressions.

**Comment by ljbade** [comment]
@springmeyer not sure why the build is failing with the missing `std::end` `std::begin` on Travis. Compiles fine on my machine.

**Comment by springmeyer** [comment]
This pull has merit, but before being ready would need 1) unit tests, 2) gut check to make sure performance is not impacted (and if it is, some quicker method to skip the `std::find` if not needed).

**Comment by flippmoke** [comment]
Closing this pull request because it is so far behind master.

**Pull request closed without merging**
