### PR TITLE
Add tilecompress/tileuncompress examples

### PR DESCRIPTION
**Pull request by strk**

### CODE REVIEW

**Comment by springmeyer** [comment]
Not seeing a lot of value added by this because the current tileinfo (and other tools) can transparently handle compressed or uncompressed tiles.

**Comment by strk** [comment]
sorry I'm getting back to this, but as I got asked to look at how to optimize vector tiles and having again some need for debugging tools I've landed here and now wondering why wasn't this PR accepted.

You're saying `tileinfo` can transparently handle compressed/uncompressed tiles but these example executables are for actually changing the compression state of files stored on a machine, what's wrong with having them as examples ? Are there other tools doing that ?

**Comment by flippmoke** [comment]
@strk you can use `gzip` from the command line or `gunzip`. 

```sh
$ ./build/Release/tileinfo test/data/0.0.0.vector-b.mvt 
message: appears not to be compressed
layers: 1
water:
  version: 2
  extent: 4096
  features: 5
  keys: 1
  values: 1
  geometry summary:
    total: 2455
    commands: 207
    move_to: 69
    line_to: 1055
    close: 69
    degenerate polygons: 0
    empty geoms: 0
$ gzip test/data/0.0.0.vector-b.mvt 
$ ./build/Release/tileinfo test/data/0.0.0.vector-b.mvt.gz 
message: gzip compressed
layers: 1
water:
  version: 2
  extent: 4096
  features: 5
  keys: 1
  values: 1
  geometry summary:
    total: 2455
    commands: 207
    move_to: 69
    line_to: 1055
    close: 69
    degenerate polygons: 0
    empty geoms: 0
```

**Comment by flippmoke** [comment]
You might also be interested by https://github.com/mapbox/vector-tile-spec/issues/27

**Pull request closed without merging**
