### PR TITLE
V2 spec

### PR DESCRIPTION
**Pull request by springmeyer**
Implementation of https://github.com/mapbox/vector-tile-spec/tree/master/2.0

### CODE REVIEW

**Comment by springmeyer** [comment]
@flippmoke we spoke earlier about this branch being blocked by compiles not yet working on travis due to outdated `mapnik-latest` mason packages. Well, they are now updated for OS X. Dude to llvm.org being offline today that prevented the linux packages from getting built. Once someone commits to mapnik master again and the linux builds work then `mapnik-latest` packages will be available for both platforms.

**Comment by springmeyer** [comment]
Okay, packages are updated. Now the travis test failures are something to do with comparison of geojson strings (https://travis-ci.org/mapbox/mapnik-vector-tile/jobs/100448532#L782). Back to @flippmoke to figure these out.

**Comment by flippmoke** [comment]
@springmeyer @artemp https://travis-ci.org/mapbox/mapnik-vector-tile/jobs/100645511 had a failure -- this is due to the memory leaking issues in mapnik. This will continue until randomly on some builds until https://github.com/mapnik/mapnik/pull/3219 is merged into master and mason is rebuilt.

**Comment by springmeyer** [comment]
> @springmeyer @artemp https://travis-ci.org/mapbox/mapnik-vector-tile/jobs/100645511 had a failure -- this is due to the memory leaking issues in mapnik. This will continue until randomly on some builds until mapnik/mapnik#3219 is merged into master and mason is rebuilt.

Hmm, what evidence do we have that https://github.com/mapnik/mapnik/pull/3219 fixes. If it fixes then why?

**Comment by flippmoke** [comment]
@springmeyer memory errors notified by `-fsanitize=address` and changing the line removes the errors we are seeing. @artemp looked into this a couple days ago.

**Pull request merged**
