### PR TITLE
Using SSE SIMD in Simplification

### PR DESCRIPTION
**Pull request by flippmoke**
A speed improvement in the simplification code by using SSE code.
## Master Bench

```
./build/Release/vtile-encode ./test/geometry-test-data/benchmark/ginormous-polygon.json 0 0 0 -i 100 -p 4326
z:0 x:0 y:0 iterations:100
5421.31ms (cpu 5407.38ms)   | encode tile: ./test/geometry-test-data/benchmark/ginormous-polygon.json
```
## Pull Request Bench

```
./build/Release/vtile-encode ./test/geometry-test-data/benchmark/ginormous-polygon.json 0 0 0 -i 100 -p 4326
z:0 x:0 y:0 iterations:100
3009.47ms (cpu 2998.82ms)   | encode tile: ./test/geometry-test-data/benchmark/ginormous-polygon.json
```

/cc @springmeyer @artemp @jakepruitt

### CODE REVIEW

**Comment by pnorman** [comment]
Will this continue to work on non-x86 platforms?

**Comment by flippmoke** [comment]
@pnorman if we decided to accept this pull request we could add a compile flag to use the original functionality. It should work just fine on x64 as well

**Comment by pnorman** [comment]
cc @sebastic since I think he's packaging mapnik-vector-tile on other CPUs

**Comment by sebastic** [comment]
The mapnik-vector-tile source package builds an architecture independent binary package, so the build is only performed on the architecture of the build system which is amd64 in my case. The node-mapnik package may be affected by this if it's arch:any, it's the reason we have mapnik-vector-tile packaged.

**Comment by flippmoke** [comment]
```
./build/Release/vtile-encode ./test/geometry-test-data/benchmark/ginormous-polygon.json 0 0 0 -i 100 -p 4326
z:0 x:0 y:0 iterations:100
2959.72ms (cpu 2936.32ms)   | encode tile: ./test/geometry-test-data/benchmark/ginormous-polygon.json
```

**Comment by pnorman** [comment]
This PR seems oddly large, like a merge or rebase screwed up

**Comment by flippmoke** [comment]
@pnorman a screw up in a rebase

**Comment by flippmoke** [comment]
Closed in favor of #268

**Pull request closed without merging**
